basePath: /
definitions:
  models.Order:
    properties:
      id:
        format: uuid
        type: string
      items:
        items:
          $ref: '#/definitions/models.OrderItem'
        type: array
    required:
    - id
    - items
    type: object
  models.OrderItem:
    properties:
      product:
        $ref: '#/definitions/models.Product'
      quantity:
        format: int32
        minimum: 1
        type: integer
    required:
    - product
    - quantity
    type: object
  models.Product:
    properties:
      description:
        maxLength: 255
        type: string
      id:
        format: uuid
        type: string
      image_path:
        maxLength: 255
        type: string
      price:
        format: float
        minimum: 0
        type: number
      title:
        maxLength: 255
        type: string
    required:
    - description
    - id
    - image_path
    - price
    - title
    type: object
  utils.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: max.guzman@icloud.com
    name: Max Guzman
  description: A fun sticker store REST API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://swagger.io/terms/
  title: Stickerfy API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all exists orders.
      operationId: get-all-orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: get all exists orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create a new order.
      operationId: create-new-order
      parameters:
      - description: Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: create a new order
      tags:
      - orders
  /products:
    delete:
      consumes:
      - application/json
      description: Delete product.
      operationId: delete-product
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Get all exists products.
      operationId: get-all-products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: get all exists products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product.
      operationId: create-product
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: create a new product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product.
      operationId: update-product
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: update product
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Get product by given ID.
      operationId: get-product-by-id
      parameters:
      - description: Product ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
        x-example: 4a7cdb5c-bd2a-47f6-9d4a-3531b110d26d
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: get product by given ID
      tags:
      - products
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Products API
  name: products
- description: Orders API
  name: orders
