basePath: /
definitions:
  models.Order:
    properties:
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/models.OrderItem'
        type: array
    required:
    - id
    - items
    type: object
  models.OrderItem:
    properties:
      product:
        $ref: '#/definitions/models.Product'
      quantity:
        format: int32
        minimum: 1
        type: integer
    required:
    - product
    - quantity
    type: object
  models.Product:
    properties:
      description:
        maxLength: 255
        type: string
      id:
        type: string
      image_path:
        maxLength: 255
        type: string
      price:
        format: float
        minimum: 0
        type: number
      title:
        maxLength: 255
        type: string
    required:
    - description
    - id
    - image_path
    - price
    - title
    type: object
host: localhost:8000
info:
  contact:
    email: max.guzman@icloud.com
    name: Max Guzman
  description: A fun sticker store REST API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://swagger.io/terms/
  title: Stickerfy API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all exists orders.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: get all exists orders
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: Create a new order.
      parameters:
      - description: Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: create a new order
      tags:
      - Order
  /products:
    delete:
      consumes:
      - application/json
      description: Delete product.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: delete product
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Get all exists products.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: get all exists products
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: Create a new product.
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: create a new product
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update product.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: update product
      tags:
      - Product
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Get product by given ID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: get product by given ID
      tags:
      - Product
swagger: "2.0"
