global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: stickerfy
    static_configs:
      - targets: ["stickerfy-api:8000"]
        labels:
          app: stickerfy
          env: dev
