name: Run go tests
run-name: Automated tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Test
        run: |
          go test -v -timeout 30s -coverprofile=cover.out -cover ./...
      - name: Coverage
        run: |
          go tool cover -func=cover.out
