name: Run pre-build checks
run-name: Code audit, security scanner and linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prebuild-chechs:
    name: prebuild-chechs
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Install go-critic
        run: |
          go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
      - name: Run code audit
        run: |
          gocritic check -enableAll ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
      - name: golangci-lint
        run: |
          golangci-lint run ./... --timeout 5m
