name: golangci-lint
run-name: Code linting with golangci-lint

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - run: go get -u
      - run: export GO111MODULE=on
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
