name: golangci-lint
run-name: ${{ github.actor }} is checking code with golangci-lint

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - run: go mod tidy
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
