name: Run golangci-lint
run-name: Code linting with golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51.1
          skip-go-installation: true
          args: --timeout 5m
